[modules.utils.submodules]
math_helper = '\\?\D:\projects\rust\nlang\test_game\src\utils\math_helper.nlang'
formatter = '\\?\D:\projects\rust\nlang\test_game\src\utils\formatter.nlang'

[modules.game.submodules]
stats = '\\?\D:\projects\rust\nlang\test_game\src\game\stats.nlang'
emotes = '\\?\D:\projects\rust\nlang\test_game\src\game\emotes.nlang'
inventory = '\\?\D:\projects\rust\nlang\test_game\src\game\inventory.nlang'
character = '\\?\D:\projects\rust\nlang\test_game\src\game\character.nlang'

[modules.ui.submodules]
display = '\\?\D:\projects\rust\nlang\test_game\src\ui\display.nlang'
menu = '\\?\D:\projects\rust\nlang\test_game\src\ui\menu.nlang'
